plugins {
    id 'java'
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation project(':common')
    compileOnly 'io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT'
    compileOnly 'com.mojang:authlib:6.0.55'
}

jar {
    destinationDirectory = file("$projectDir/target")
    archiveFileName = "${project.name}-${project.version}.jar"
}